# Generated by Django 2.1.3 on 2018-11-26 08:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('enduser_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='终端用户UID')),
                ('cellphone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号码')),
                ('phone_area', models.CharField(blank=True, default='+86', max_length=10, null=True, verbose_name='归属地')),
                ('email', models.EmailField(blank=True, max_length=256, null=True, verbose_name='邮箱')),
                ('nick_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='昵称')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='性别')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='所在城市')),
                ('avatar', models.CharField(blank=True, max_length=512, null=True, verbose_name='头像')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='is activation')),
                ('is_virtual', models.BooleanField(default=False, verbose_name='是否虚拟')),
                ('is_online', models.BooleanField(default=False, verbose_name='在线状态')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is delete')),
                ('iot_secret', models.CharField(max_length=50, verbose_name='IOT秘钥')),
                ('online_times', models.IntegerField(default=0, verbose_name='上线次数')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(db_column='app_id', on_delete=django.db.models.deletion.CASCADE, to='app.App', verbose_name='application')),
            ],
            options={
                'db_table': 'enduser',
            },
        ),
        migrations.AlterUniqueTogether(
            name='enduser',
            unique_together={('app', 'cellphone')},
        ),
    ]
