# Generated by Django 2.1.3 on 2018-11-26 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enduser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True, verbose_name='faq content')),
                ('image', models.CharField(blank=True, max_length=150, null=True, verbose_name='image')),
                ('status', models.SmallIntegerField(choices=[(1, 'has been handled'), (2, "hasn't been handled")], default=2, verbose_name='status')),
                ('delete_flag', models.SmallIntegerField(default=0, verbose_name='delete flag')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('user', models.ForeignKey(db_column='enduser_id', on_delete=django.db.models.deletion.CASCADE, to='enduser.EndUser', verbose_name='create_user')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=30, verbose_name='help question')),
                ('answer', models.TextField(verbose_name='help answer')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='help type')),
                ('delete_flag', models.SmallIntegerField(default=0, verbose_name='delete flag')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
            options={
                'db_table': 'support',
            },
        ),
    ]
