# Generated by Django 2.1.3 on 2018-11-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha', models.CharField(max_length=6)),
                ('c_type', models.CharField(choices=[('0', 'web'), ('1', 'app'), ('2', 'device')], max_length=1, verbose_name='captcha type')),
                ('account', models.CharField(blank=True, max_length=16, null=True)),
                ('app_id', models.CharField(blank=True, max_length=32, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'captcha',
            },
        ),
    ]
