# Generated by Django 2.1.3 on 2018-11-26 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_captcha'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=40)),
                ('refresh_token', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_user_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
